on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Code
      uses: actions/checkout@v2

    - name: Build and Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: a2m1/debian
        tags: stable-slim-ssh-client
        # tag_with_ref: true
        # tag_with_sha: true